configure: drop --without-clock-gettime option
clock_gettime() is now a hard requirement. Remove the
--without-clock-gettime option from the configure script to avoid
allowing the build to fail.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -127,7 +127,6 @@ For better control, use the options below.
   --without-seccomp      Don't use seccomp even if it is available
   --disable-forcednsretry Don't retry on permanent DNS error
   --without-aes-gcm-siv  Don't use AES-GCM-SIV for NTS even if it is available
-  --without-clock-gettime Don't use clock_gettime() even if it is available
   --disable-timestamping Disable support for SW/HW timestamping
   --enable-ntp-signd     Enable support for MS-SNTP authentication in Samba
   --with-ntp-era=SECONDS Specify earliest assumed NTP time in seconds
@@ -244,7 +243,6 @@ try_setsched=0
 try_lockmem=0
 feat_forcednsretry=1
 try_aes_gcm_siv=1
-try_clock_gettime=1
 try_arc4random=1
 try_recvmmsg=1
 feat_timestamping=1
@@ -341,9 +339,6 @@ do
     ;;
     --without-aes-gcm-siv)
       try_aes_gcm_siv=0
-    ;;
-    --without-clock-gettime)
-      try_clock_gettime=0
     ;;
     --disable-timestamping)
       feat_timestamping=0
@@ -678,20 +673,18 @@ then
   fi
 fi
 
-if [ $try_clock_gettime = "1" ]; then
-  if ! test_code 'clock_gettime()' 'time.h' '' '' '
+if ! test_code 'clock_gettime()' 'time.h' '' '' '
+  struct timespec ts;
+  clock_gettime(CLOCK_REALTIME, &ts);'
+then
+  if test_code 'clock_gettime() in -lrt' 'time.h' '' '-lrt' '
     struct timespec ts;
     clock_gettime(CLOCK_REALTIME, &ts);'
   then
-    if test_code 'clock_gettime() in -lrt' 'time.h' '' '-lrt' '
-      struct timespec ts;
-      clock_gettime(CLOCK_REALTIME, &ts);'
-    then
-      EXTRA_LIBS="$EXTRA_LIBS -lrt"
-    else
-      echo "error: clock_gettime() not found"
-      exit 1
-    fi
+    EXTRA_LIBS="$EXTRA_LIBS -lrt"
+  else
+    echo "error: clock_gettime() not found"
+    exit 1
   fi
 fi
 
